apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "code-valet"
  labels:
    app.kubernetes.io/name: "code-valet"
    app.kubernetes.io/version: "0.0.1"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "code-valet"
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
  descriptor:
    version: "1.0.0"
    description: "Code Valet"
    icons: 
      - src: "https://www.codevalet.com/logo.png"
        type: "image/png"
    type: code-valet
    links:
      - description: 🔗 Open Code Valet
        url: "https://codevalet.com"
#      - description: Slackernews Admin
