apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "slackernews"
  labels:
    app.kubernetes.io/name: "slackernews"
    app.kubernetes.io/version: "0.0.1"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "slackernews"
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
  descriptor:
    version: "1.0.0"
    description: "BMC Helix"
    icons:
      - src: "https://banner2.cleanpng.com/20180419/ziw/kisspng-bmc-software-remedy-corporation-it-service-managem-china-cloud-5ad8a74ec038a0.1950217715241480467873.jpg"
        type: "image/jpeg"
    type: bmc-helix
    links:
      - description: 🔗 Open BMC Helix
        url: "https://bmc-helix"
#      - description: BMC Admin
