apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "code-valet"
  labels:
    app.kubernetes.io/name: "code-valet"
    app.kubernetes.io/version: "0.0.1"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "code-valet"
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
  descriptor:
    version: "1.0.0"
    description: "Code Valet"
    icons: 
      - src: "https://media.licdn.com/dms/image/v2/D4D3DAQEBaPgCgdvZsg/image-scale_191_1128/B4DZZo5vHgHwAo-/0/1745516690081/codevalet_cover?e=1754290800&v=beta&t=6dJc72MB4Cdm8Fj2yyHI66Wl1fHLNnbWQS7v9BnU8QA"
        type: "image/jpeg"
    type: code-valet
    links:
      - description: 🔗 Open Code Valet
        url: "https://codevalet.com"
#      - description: Slackernews Admin
