apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: anaconda
spec:
  title: Anaconda
  icon: "https://www.bigdatawire.com/wp-content/uploads/2022/04/anaconda_logo-768x342.png"
  ports:
    - serviceName: anaconda-nginx
      servicePort: 443
      localPort: 443
      applicationUrl: "https://anaconda"
  statusInformers:
    - deployment/slackernews
    - deployment/slackernews-nginx
    - '{{repl if ConfigOptionEquals "deploy_postgres" "1"}}statefulset/postgres{{repl end}}'
