{{ if .Values.service.tls.enabled }}
{{ if not .Values.service.tls.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: code-valet-nginx
type: kubernetes.io/tls
data:
  tls.crt: {{ required "A valid .Values.service.tls.cert is required" .Values.service.tls.cert | b64enc }}
  tls.key: {{ required "A valid .Values.service.tls.key is required" .Values.service.tls.key | b64enc }}
{{ end }}
{{ end }}
