apiVersion: v1
kind: Service
metadata:
  labels:
    app: code-valet-nginx
  name: code-valet-nginx
spec:
  ports:
  - name: http
{{ if .Values.service.tls.enabled }}
    port: 443
    targetPort: https
  {{- if ne .Values.nginx.service.nodePort.port nil }}
    nodePort: {{ .Values.nginx.service.nodePort.port }}
  {{- end }}
{{ else }}
    port: 8080
    targetPort: http
  {{- if ne .Values.nginx.service.nodePort.port nil }}
    nodePort: {{ .Values.nginx.service.nodePort.port }}
  {{- end }}
{{ end }}
  selector:
    app: code-valet-nginx
  type: {{ .Values.nginx.service.type }}
