apiVersion: v1
kind: Service
metadata:
  labels:
    app: code-valet
  name: code-valet
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: code-valet
  type: ClusterIP
